# Generated by Django 2.0.6 on 2018-06-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('account_name', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=53, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
