# Generated by Django 2.0.6 on 2018-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinbaseEvent',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField()),
                ('locally_created_at', models.DateTimeField(auto_now_add=True)),
                ('api_version', models.CharField(max_length=512)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='purchase',
            name='public_key',
            field=models.CharField(default='', max_length=53),
            preserve_default=False,
        ),
    ]
