# Generated by Django 2.0.6 on 2018-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_auto_20180616_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eos_usd', models.FloatField()),
                ('ram_kb_eos', models.FloatField()),
            ],
        ),
    ]
