# Generated by Django 2.0.6 on 2018-06-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_auto_20180616_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='account_created',
            field=models.BooleanField(default=False),
        ),
    ]
