# Generated by Django 2.0.6 on 2018-06-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0005_purchase_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
