# Generated by Django 2.0.6 on 2018-06-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0006_purchase_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
