# Generated by Django 2.0.6 on 2018-06-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0010_auto_20180619_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stripe',
            field=models.DateTimeField(null=True),
        ),
    ]
