# Generated by Django 2.0.6 on 2018-06-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0014_auto_20180622_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='public_key',
        ),
    ]
