# Generated by Django 2.0.6 on 2018-07-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0015_remove_purchase_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cogs_cents',
            field=models.IntegerField(null=True),
        ),
    ]
