# Generated by Django 2.0.6 on 2018-07-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0016_purchase_cogs_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='profit',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
            preserve_default=False,
        ),
    ]
