# Generated by Django 2.0.6 on 2018-07-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0017_purchase_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price_cents',
            new_name='price_cents_credit',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_cents_crypto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_eos_eos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
