# Generated by Django 2.0.6 on 2018-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0018_auto_20180730_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_eos_eos',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
