# Generated by Django 2.0.6 on 2018-08-23 21:27

import buy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0019_auto_20180730_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='nonce',
            field=models.CharField(default=buy.models.get_nonce, max_length=53),
        ),
    ]
