# Generated by Django 2.1.2 on 2018-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0021_purchase_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
