# Generated by Django 2.1.2 on 2018-10-15 12:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0022_vatrates'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
