# Generated by Django 2.1.2 on 2018-10-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0023_purchase_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cogs_cents',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price_cents_credit',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price_cents_crypto',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price_eos_eos',
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'credit'), ('crypto', 'crypto')], max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_gross',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_net',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
