# Generated by Django 2.1.2 on 2018-10-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0024_auto_20181015_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='country',
            new_name='country_from_ip',
        ),
    ]
