# Generated by Django 2.1.2 on 2018-10-15 16:41

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0025_auto_20181015_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='country_given',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
