<ul class="breadcrumbs">
  <li class="{% if breadcrumbs_account_name %}active{% endif %}{% if breadcrumbs_choose_finished%} finished{% endif %}">Choose Account Name</li>
  <li class="{% if breadcrumbs_public_keys %}active{% endif %}{% if breadcrumbs_keys_finished%} finished{% endif %}">Provide Public Keys</li>
  <li class="{% if breadcrumbs_payment %}active{% endif %}{% if breadcrumbs_purchase_finished%} finished{% endif %}">Payment</li>
</ul>