{% include 'buy/keys_help.inc' %}

<h4>Why do I need two keys, owner and active?</h4>
<p>The active key is the one you're gonna use for daily operations like interacting with dApps or money transfers. This would be the key that you're gonna import into your favorite wallet or Scatter if you want to interact with dApps. If this key gets compromised, you will be able to regain control of your account using the owner key and cancel outgoing transfers that haven't gone through yet.<p>
<p>The owner key is very important as whoever holds it is the real owner of the account. You will need it if you want to transfer control of the account to someone else. You can also use it to change the keys of your account. You can also use it to prove ownership of your account in case your active key gets compromised. That's why you should generate this key in an offline key generator in only store it in cold storage.
</p>
